config/routes.rb
Rails.application.routes.draw do
  resources :items do
    post :purchase, on: :member
  end

  

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  
    root 'items#index'
    

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates_numericality_of :quantity, greater_than: 0
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable
  attr_accessor :login
  has_many :items
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :set_device_type

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

  def set_device_type
    request.variant = :phone if browser.mobile?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :purchase]
  before_action :authenticate_user!
  before_action :user_signed_in?

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(purchased: [false, nil]).order('created_at DESC')
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to new_item_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to root_path, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purchase  
    @item.toggle!(:purchased)
    @item.save
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:user_id, :name, :purchased, :quantity)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <% if user_signed_in? %>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <% end %>
    
    <%= link_to "Shopping List", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
    
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">

              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>

    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/elements/_navbar_phone.html.erb
<div data-role="header" data-position="fixed" data-theme="b">
  <h1>Der Einkaufer</h1>
<!--  <a href="/signout" data-icon="gear" data-transition data-rel="dialog">Sign out</a> -->
  <div data-role="navbar" data-iconpos="left">
    <ul>
      <li><a href="/" data-icon="home" data-ajax="false">Home</a></li>
      <li><a href="/items/new" data-icon="plus" data-transition="slide">Add Item</a></li>

    </ul>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => 'form-horizontal form-model', remote: true } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :quantity, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to "Cancel", root_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/items/_item.html+phone.erb
<tr 
data-link="<%= purchase_item_path(item) %>",  
class="<%= "purchased" if item.purchased? %>">
	<td><%= item.name %> (<%= item.quantity %>)</td>
	<td><%=l item.created_at, format: :short %> by <%= item.user.username %></td>
	<td><%= link_to '', edit_item_path(item.id), :class => 'fa fa-pencil' %></td>
</tr>

app/views/items/_item.html.erb
	<tr 
	data-link="<%= purchase_item_path(item) %>",  
	class="<%= "purchased" if item.purchased? %>">
		<td><%= item.name %> (<%= item.quantity %>)</td>
		<td><%=l item.created_at, format: :short %> by <%= item.user.username %></td>
		<td><%= link_to '', edit_item_path(item.id), :class => 'fa fa-pencil' %></td>
	</tr>
	

app/views/items/create.js.erb
<% if @item.new_record? %>
	$('input#item_name, input#item_quantity').effect('highlight', { color: 'red' });
<% else %>
	$('tbody#items').prepend("<%= escape_javascript(render @item) %>");
	$('tbody tr').first().effect('highlight');
	$('input#item_name').val('');
	$('input#item_quantity').val('1');
<% end %> 

app/views/items/edit.html.erb
<div class="page-header">
  <h1>Edit "<%= @item.name %>"</h1>
</div>
<%= render :partial => 'form' %>

<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/items/index.html+phone.erb
<div data-role="content">
  <table id="items" class="table">
	  <tbody id="items">
	    <%= render @items %>
	  </tbody>
  </table>
</div>

app/views/items/index.html.erb
<%- model_class = Item -%>

<%= form_for(Item.new, remote: true) do |f| %>
  <div class="form-group">
    <div class="field">
      <%= f.label :name, :class => 'control-label col-md-2' %>
      <%= f.text_field :name, :class => 'text-field form-control' %>
      <%= f.label :quantity, :class => 'control-label col-md-2' %> 
      <%= f.number_field :quantity, :class => 'text-field form-control' %>
    </div>
    <div class='actions'>
        <%= f.submit :class => 'btn btn-primary'%>
    </div>
  </div>
<% end %> 




<table id="items" class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th>Created</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="items">
    <%= render @items %>
  </tbody>
</table>

app/views/items/new.html+phone.erb
<%= form_for(Item.new, remote: true) do |f| %>
  
<div class="form">
  <div data-role="fieldcontain">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :quantity %> 
    <%= f.number_field :quantity %>
  </div>
</div>
<div class='actions'>
    <%= f.submit %>
</div>
  
<% end %> 

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping List</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <%= stylesheet_link_tag "http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "http://code.jquery.com/jquery-1.8.2.min.js" %>
  <%= javascript_include_tag "http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'mb-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
</head>
<body>
	<div data-role="page">
		<%= render partial: "elements/navbar_phone" %>
	  <div class="container">
		<%= yield %>
	  </div>	
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>


</head>
<body>
<div class="container well">
	<%= render partial: "elements/navbar" %>
	<%= bootstrap_flash %>

	<%= yield %>
</div>
</body>
</html>

app/views/not_used_delete_later/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Item %></h1>
</div>
<%= render :partial => 'form' %>

app/views/not_used_delete_later/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => Item %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @item.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:purchased) %></dt>
      <dd><pre class="prettyprint"><%= @item.purchased %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:quantity) %></dt>
      <dd><pre class="prettyprint"><%= @item.quantity %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>